import "./globals.css";
import { Red_Hat_Text } from "next/font/google";

const redhat = Red_Hat_Text({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${redhat.className} bg-stars bg-verydarkblue`}>
        {children}
      </body>
    </html>
  );
}
